# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_Movie.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_newMovie(object):
    def setupUi(self, newMovie):
        newMovie.setObjectName("newMovie")
        newMovie.resize(391, 281)
        newMovie.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.gridLayoutWidget = QtWidgets.QWidget(newMovie)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 80, 371, 151))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Animation = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.Animation.setObjectName("Animation")
        self.gridLayout.addWidget(self.Animation, 2, 0, 1, 1)
        self.Action = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.Action.setObjectName("Action")
        self.gridLayout.addWidget(self.Action, 0, 0, 1, 1)
        self.Children = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.Children.setObjectName("Children")
        self.gridLayout.addWidget(self.Children, 3, 0, 1, 1)
        self.Adventure = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.Adventure.setObjectName("Adventure")
        self.gridLayout.addWidget(self.Adventure, 1, 0, 1, 1)
        self.SciFi = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.SciFi.setObjectName("SciFi")
        self.gridLayout.addWidget(self.SciFi, 0, 3, 1, 1)
        self.Western = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.Western.setObjectName("Western")
        self.gridLayout.addWidget(self.Western, 3, 3, 1, 1)
        self.Romance = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.Romance.setObjectName("Romance")
        self.gridLayout.addWidget(self.Romance, 4, 2, 1, 1)
        self.Thriller = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.Thriller.setObjectName("Thriller")
        self.gridLayout.addWidget(self.Thriller, 1, 3, 1, 1)
        self.War = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.War.setObjectName("War")
        self.gridLayout.addWidget(self.War, 2, 3, 1, 1)
        self.Mystery = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.Mystery.setObjectName("Mystery")
        self.gridLayout.addWidget(self.Mystery, 3, 2, 1, 1)
        self.IMAX = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.IMAX.setObjectName("IMAX")
        self.gridLayout.addWidget(self.IMAX, 1, 2, 1, 1)
        self.Horror = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.Horror.setObjectName("Horror")
        self.gridLayout.addWidget(self.Horror, 0, 2, 1, 1)
        self.Fantasy = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.Fantasy.setObjectName("Fantasy")
        self.gridLayout.addWidget(self.Fantasy, 3, 1, 1, 1)
        self.Drama = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.Drama.setObjectName("Drama")
        self.gridLayout.addWidget(self.Drama, 2, 1, 1, 1)
        self.FilmNoir = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.FilmNoir.setObjectName("FilmNoir")
        self.gridLayout.addWidget(self.FilmNoir, 4, 1, 1, 1)
        self.Documentary = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.Documentary.setObjectName("Documentary")
        self.gridLayout.addWidget(self.Documentary, 1, 1, 1, 1)
        self.Comedy = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.Comedy.setObjectName("Comedy")
        self.gridLayout.addWidget(self.Comedy, 4, 0, 1, 1)
        self.Crime = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.Crime.setObjectName("Crime")
        self.gridLayout.addWidget(self.Crime, 0, 1, 1, 1)
        self.Musical = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.Musical.setObjectName("Musical")
        self.gridLayout.addWidget(self.Musical, 2, 2, 1, 1)
        self.Confirm = QtWidgets.QPushButton(newMovie)
        self.Confirm.setGeometry(QtCore.QRect(160, 240, 75, 23))
        self.Confirm.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.Confirm.setObjectName("Confirm")
        self.MovieName = QtWidgets.QPlainTextEdit(newMovie)
        self.MovieName.setGeometry(QtCore.QRect(10, 30, 241, 31))
        self.MovieName.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.MovieName.setObjectName("MovieName")
        self.MovieYear = QtWidgets.QPlainTextEdit(newMovie)
        self.MovieYear.setGeometry(QtCore.QRect(290, 30, 91, 31))
        self.MovieYear.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.MovieYear.setObjectName("MovieYear")

        self.retranslateUi(newMovie)
        QtCore.QMetaObject.connectSlotsByName(newMovie)

    def retranslateUi(self, newMovie):
        _translate = QtCore.QCoreApplication.translate
        newMovie.setWindowTitle(_translate("newMovie", "Dialog"))
        self.Animation.setText(_translate("newMovie", "Animation"))
        self.Action.setText(_translate("newMovie", "Action"))
        self.Children.setText(_translate("newMovie", "Children"))
        self.Adventure.setText(_translate("newMovie", "Adventure"))
        self.SciFi.setText(_translate("newMovie", "Sci-Fi"))
        self.Western.setText(_translate("newMovie", "Western"))
        self.Romance.setText(_translate("newMovie", "Romance"))
        self.Thriller.setText(_translate("newMovie", "Thriller"))
        self.War.setText(_translate("newMovie", "War"))
        self.Mystery.setText(_translate("newMovie", "Mystery"))
        self.IMAX.setText(_translate("newMovie", "IMAX"))
        self.Horror.setText(_translate("newMovie", "Horror"))
        self.Fantasy.setText(_translate("newMovie", "Fantasy"))
        self.Drama.setText(_translate("newMovie", "Drama"))
        self.FilmNoir.setText(_translate("newMovie", "Film-Noir"))
        self.Documentary.setText(_translate("newMovie", "Documentary"))
        self.Comedy.setText(_translate("newMovie", "Comedy"))
        self.Crime.setText(_translate("newMovie", "Crime"))
        self.Musical.setText(_translate("newMovie", "Musical"))
        self.Confirm.setText(_translate("newMovie", "Confirm"))
        self.MovieName.setPlainText(_translate("newMovie", "Movie Name"))
        self.MovieYear.setPlainText(_translate("newMovie", "Year"))

