# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CSS498_Project.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MovieManager(object):
    def setupUi(self, MovieManager):
        MovieManager.setObjectName("MovieManager")
        MovieManager.resize(871, 619)
        MovieManager.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.MoviesButton = QtWidgets.QPushButton(MovieManager)
        self.MoviesButton.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.MoviesButton.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.MoviesButton.setObjectName("MoviesButton")
        self.ClientsButton = QtWidgets.QPushButton(MovieManager)
        self.ClientsButton.setGeometry(QtCore.QRect(100, 10, 75, 23))
        self.ClientsButton.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.ClientsButton.setObjectName("ClientsButton")
        self.gridLayoutWidget = QtWidgets.QWidget(MovieManager)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(511, 10, 351, 151))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Children = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.Children.setObjectName("Children")
        self.gridLayout.addWidget(self.Children, 3, 0, 1, 1)
        self.Animation = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.Animation.setObjectName("Animation")
        self.gridLayout.addWidget(self.Animation, 2, 0, 1, 1)
        self.Action = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.Action.setObjectName("Action")
        self.gridLayout.addWidget(self.Action, 0, 0, 1, 1)
        self.Adventure = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.Adventure.setObjectName("Adventure")
        self.gridLayout.addWidget(self.Adventure, 1, 0, 1, 1)
        self.Western = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.Western.setObjectName("Western")
        self.gridLayout.addWidget(self.Western, 3, 3, 1, 1)
        self.War = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.War.setObjectName("War")
        self.gridLayout.addWidget(self.War, 2, 3, 1, 1)
        self.Thriller = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.Thriller.setObjectName("Thriller")
        self.gridLayout.addWidget(self.Thriller, 1, 3, 1, 1)
        self.SciFi = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.SciFi.setObjectName("SciFi")
        self.gridLayout.addWidget(self.SciFi, 0, 3, 1, 1)
        self.Romance = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.Romance.setObjectName("Romance")
        self.gridLayout.addWidget(self.Romance, 4, 2, 1, 1)
        self.Mystery = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.Mystery.setObjectName("Mystery")
        self.gridLayout.addWidget(self.Mystery, 3, 2, 1, 1)
        self.Musical = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.Musical.setObjectName("Musical")
        self.gridLayout.addWidget(self.Musical, 2, 2, 1, 1)
        self.IMAX = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.IMAX.setObjectName("IMAX")
        self.gridLayout.addWidget(self.IMAX, 1, 2, 1, 1)
        self.Horror = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.Horror.setObjectName("Horror")
        self.gridLayout.addWidget(self.Horror, 0, 2, 1, 1)
        self.FilmNoir = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.FilmNoir.setObjectName("FilmNoir")
        self.gridLayout.addWidget(self.FilmNoir, 4, 1, 1, 1)
        self.Fantasy = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.Fantasy.setObjectName("Fantasy")
        self.gridLayout.addWidget(self.Fantasy, 3, 1, 1, 1)
        self.Drama = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.Drama.setObjectName("Drama")
        self.gridLayout.addWidget(self.Drama, 2, 1, 1, 1)
        self.Documentary = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.Documentary.setObjectName("Documentary")
        self.gridLayout.addWidget(self.Documentary, 1, 1, 1, 1)
        self.Crime = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.Crime.setObjectName("Crime")
        self.gridLayout.addWidget(self.Crime, 0, 1, 1, 1)
        self.Comedy = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.Comedy.setObjectName("Comedy")
        self.gridLayout.addWidget(self.Comedy, 4, 0, 1, 1)
        self.ReturnButton = QtWidgets.QPushButton(MovieManager)
        self.ReturnButton.setGeometry(QtCore.QRect(10, 50, 75, 23))
        self.ReturnButton.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.ReturnButton.setObjectName("ReturnButton")
        self.RentButton = QtWidgets.QPushButton(MovieManager)
        self.RentButton.setGeometry(QtCore.QRect(100, 50, 75, 23))
        self.RentButton.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.RentButton.setObjectName("RentButton")
        self.SearchBar = QtWidgets.QPlainTextEdit(MovieManager)
        self.SearchBar.setGeometry(QtCore.QRect(100, 130, 271, 31))
        self.SearchBar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SearchBar.setObjectName("SearchBar")
        self.Display = QtWidgets.QTextEdit(MovieManager)
        self.Display.setGeometry(QtCore.QRect(190, 10, 181, 61))
        self.Display.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Display.setObjectName("Display")
        self.SelectButton = QtWidgets.QPushButton(MovieManager)
        self.SelectButton.setGeometry(QtCore.QRect(10, 90, 81, 31))
        self.SelectButton.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.SelectButton.setObjectName("SelectButton")
        self.SearchButton = QtWidgets.QPushButton(MovieManager)
        self.SearchButton.setGeometry(QtCore.QRect(10, 130, 81, 31))
        self.SearchButton.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.SearchButton.setObjectName("SearchButton")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(MovieManager)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(390, 60, 111, 101))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.name = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.name.setObjectName("name")
        self.gridLayout_2.addWidget(self.name, 1, 0, 1, 1)
        self.year = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.year.setObjectName("year")
        self.gridLayout_2.addWidget(self.year, 0, 0, 1, 1)
        self.phone = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.phone.setObjectName("phone")
        self.gridLayout_2.addWidget(self.phone, 2, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(MovieManager)
        self.textEdit.setGeometry(QtCore.QRect(390, 20, 111, 31))
        self.textEdit.setObjectName("textEdit")
        self.tableDisplay = QtWidgets.QTableWidget(MovieManager)
        self.tableDisplay.setGeometry(QtCore.QRect(10, 170, 851, 441))
        self.tableDisplay.setObjectName("tableDisplay")
        self.tableDisplay.setColumnCount(0)
        self.tableDisplay.setRowCount(0)
        self.SelectBar = QtWidgets.QPlainTextEdit(MovieManager)
        self.SelectBar.setGeometry(QtCore.QRect(100, 90, 271, 31))
        self.SelectBar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SelectBar.setObjectName("SelectBar")

        self.retranslateUi(MovieManager)
        QtCore.QMetaObject.connectSlotsByName(MovieManager)

    def retranslateUi(self, MovieManager):
        _translate = QtCore.QCoreApplication.translate
        MovieManager.setWindowTitle(_translate("MovieManager", "Dialog"))
        self.MoviesButton.setText(_translate("MovieManager", "Movies"))
        self.ClientsButton.setText(_translate("MovieManager", "Clients"))
        self.Children.setText(_translate("MovieManager", "Children"))
        self.Animation.setText(_translate("MovieManager", "Animation"))
        self.Action.setText(_translate("MovieManager", "Action"))
        self.Adventure.setText(_translate("MovieManager", "Adventure"))
        self.Western.setText(_translate("MovieManager", "Western"))
        self.War.setText(_translate("MovieManager", "War"))
        self.Thriller.setText(_translate("MovieManager", "Thriller"))
        self.SciFi.setText(_translate("MovieManager", "Sci-Fi"))
        self.Romance.setText(_translate("MovieManager", "Romance"))
        self.Mystery.setText(_translate("MovieManager", "Mystery"))
        self.Musical.setText(_translate("MovieManager", "Musical"))
        self.IMAX.setText(_translate("MovieManager", "IMAX"))
        self.Horror.setText(_translate("MovieManager", "Horror"))
        self.FilmNoir.setText(_translate("MovieManager", "Film-Noir"))
        self.Fantasy.setText(_translate("MovieManager", "Fantasy"))
        self.Drama.setText(_translate("MovieManager", "Drama"))
        self.Documentary.setText(_translate("MovieManager", "Documentary"))
        self.Crime.setText(_translate("MovieManager", "Crime"))
        self.Comedy.setText(_translate("MovieManager", "Comedy"))
        self.ReturnButton.setText(_translate("MovieManager", "Return"))
        self.RentButton.setText(_translate("MovieManager", "Rent"))
        self.SelectButton.setText(_translate("MovieManager", "Select"))
        self.SearchButton.setText(_translate("MovieManager", "Search"))
        self.name.setText(_translate("MovieManager", "Name"))
        self.year.setText(_translate("MovieManager", "Year"))
        self.phone.setText(_translate("MovieManager", "Phone Number"))
        self.textEdit.setHtml(_translate("MovieManager", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\">Search Options</span></p></body></html>"))

